name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
template: |
  # Changelog

  $CHANGES

  See details of [all code changes](https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION) since previous release.
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
exclude-paths:
  - ".github/workflows/draft-release.yml"
  - ".github/release-drafter.yml"
