name: Draft release

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  draft-release:
    if: github.repository == 'withastro/automation'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: release-drafter/release-drafter@ed4bc48ec97379be2258e7b7ac2624a3e26ab809 # v7.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
