name: Format

on:
  workflow_call:
    inputs:
      command:
        description: 'The package.json script name which will be called via "pnpm run <command>"'
        default: "format"
        required: false
        type: string

jobs:
  format:
    if: github.repository_owner == 'withastro'
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max_old_space_size=4096"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.head_ref }}
          # Needs access to push to main
          token: ${{ secrets.FREDKBOT_GITHUB_TOKEN }}

      - name: Setup PNPM
        uses: pnpm/action-setup@078e9d416474b29c0c387560859308974f7e9c53 # v6.0.1

      - name: Setup Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24.14.1
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Format code
        run: pnpm run ${{ inputs.command }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: "[ci] format"
          branch: ${{ github.head_ref }}
          commit_user_name: astrobot-houston
          commit_user_email: fred+astrobot@astro.build
          commit_author: ${{ github.event.commits[0].author.name }} <${{ github.actor }}@users.noreply.github.com>
