name: Label issues
on:
  workflow_call:

jobs:
  label_issues:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'withastro'
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["needs triage"]
            })
