name: Lockfile

on:
  workflow_call:

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code using Git
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"

      - name: Delete the existing pnpm-lock.yaml file
        run: rm pnpm-lock.yaml

      # https://github.com/pnpm/pnpm/issues/6463
      - name: Update .npmrc to update packages to latest
        run: echo "resolution-mode=highest" >> .npmrc

      - name: Create a fresh pnpm lockfile (no install)
        run: pnpm install --lockfile-only

      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v5
        with:
          branch: ci/lockfile
          # Access token is needed to trigger CI on this PR
          token: ${{ secrets.FREDKBOT_GITHUB_TOKEN }}
          commit-message: "[ci] update lockfile"
          add-paths: pnpm-lock.yaml
          title: "[ci] update lockfile"
          body: >
            This PR is auto-generated by a nightly GitHub action.
            It should automatically be merged if tests pass.
